Add generation of top-level import of original test function
While very rare, a test may actually reference another test. Currently,
however, because we effectively move the generated test into a custom
module structure, this isn't possible once the tag attribute is used.
To fix this potential problem, this change adds an import of the nested
test function at the level where the original attribute was applied.
This way, the actual function will be accessible as expected.

Note that, unfortunately, doc tests seem to perform additional magic as
part of their #[test] attribute expansion and don't even allow for this
kind of cross-referencing even without involvement of this attribute:

```rust,no_run
#[test]
fn test1() {
  assert_eq!(2 + 2, 4);
}

test1();
```

The above doc test fails to build:
```
error[E0425]: cannot find function `test1` in this scope
  --> src/lib.rs:19:1
   |
12 | test1();
   | ^^^^^ not found in this scope
```

Our attribute now suffers from a related problem and so we have to
ignore doc tests completely.